apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-app-gke
  template:
    metadata:
      labels:
        app: dynamic-app-gke
    spec:
      containers:
      - name: dynamic-app-container
        image: vaipali/my-first-repo:testapp_64
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # resources:
        #   requests:
        #     cpu: "1"
        #     memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-app-gke-svc
spec:
  selector:
    app: dynamic-app-gke
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP