apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-loadtest
  namespace: testkube
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      app: postsync-loadtest
  template:
    metadata:
      labels:
        app: postsync-loadtest
    spec:
      containers:
      - name: dynamic-app-container
        image: vaipali/my-first-repo:postsync_v0.2
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["bash /framework/kubeconfig-script.sh && testkube run test git-jmeter --watch"]

      restartPolicy: OnFailure